### ISSUE TITLE
Unexpected identifier: function rmRf

### ISSUE THREAD

**Issue by TemaSM** [MatthewNPM/rm-rf#1]
![image](https://cloud.githubusercontent.com/assets/5501615/17021223/465f5574-4f4f-11e6-8a66-71fc558e3b01.png)

**Comment by MatthewSH** [comment]
That typo missed my eyes. I never tested this module. Someone it missed me though that I misspelled `function` as `functon`. I just edited the file and will publish when I get back home. Currently on my way back from vacation.

**Comment by MatthewSH** [comment]
@TemaSM just published. Thanks for being patient!
